tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<last_name>', views.AuthorDetailView.as_view(), name='author-detail'),
]

tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/catalog/models.py
#from django.db import models
## Used to generate URLs by reversing the URL patterns.
#from django.urls import reverse
#import uuid # Required for unique book instances
#
## Create your models here.
#class Genre(models.Model):
#    """Model representing a book genre."""
#    name = models.CharField(max_length=200,
#            help_text="Enter a book genre (e.g. science fiction)")
#    def __str__(self):
#        """String for representing the Model object."""
#        return self.name
#
#class Language(models.Model):
#    """Model representing a Language (e.g. English, French, Japanese, etc.)."""
#    name = models.CharField(max_length=200,
#            help_text="Enter the book's natural language (e.g. English, French, "
#            "Japanese, etc.).")
#
#    def __str__(self):
#        """String for representing the Model object (in Admin site etc.)."""
#        return self.name
#
#
#class Book(models.Model):
#    """Model representing a book (but not a specific copy of a book)."""
#    title = models.CharField(max_length=200)
#    # Foreign key used because book can only have one author, but authoers can
#    # have multiple books.
#    # Author as a string rather than object because it hasn't been declared yet
#    # in the file.
#    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
#    summary = models.TextField(max_length=1000,
#            help_text="Enter a brief description of the book")
#    isbn = models.CharField("ISBN", max_length=13,
#            help_text='13-character '
#            '<a href="https://www.isbn-international.org/content/what-isbn">'
#            'ISBN</a>')
#    # ManyToManyField used because genre can contain many books. Books can
#    # cover many genres.
#    # Genre class has already been defined so we can specify the object above.
#    genre = models.ManyToManyField(Genre,
#            help_text="Select a genre for this book.")
#    language = models.ForeignKey("Language", on_delete=models.SET_NULL,
#            null=True)
#
#    def __str__(self):
#        """String for representing the Model object."""
#        return self.title
#
#    def get_absolute_url(self):
#        """Returns the URL to access a detail record for this book."""
#        return reverse("book-detail", args=[str(self.id)])
#
#    def display_genre(self):
#        """Create a string for the Genre. This is required to display genre in Admin."""
#        return ', '.join(genre.name for genre in self.genre.all()[:3])
#
#    display_genre.short_description = 'Genre'
#
#class BookInstance(models.Model):
#    """Model representing a specific copy of a book (i.e. that can be borrowed
#    from the library)."""
#    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
#            help_text='Unique ID for this particular book across whole library')
#    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
#    imprint = models.CharField(max_length=200)
#    due_back = models.DateField(null=True, blank=True)
#    LOAN_STATUS = (
#        ('m', 'Maintenance'),
#        ('o', 'On loan'),
#        ('a', 'Available'),
#        ('r', 'Reserved'),
#    )
#    status = models.CharField(
#        max_length=1,
#        choices=LOAN_STATUS,
#        blank=True,
#        default='m',
#        help_text='Book availability',
#    )
#
#    class Meta:
#        ordering = ['due_back']
#
#    def __str__(self):
#        """String for representing the Model object."""
#        return f'{self.id} ({self.book.title})'
#
#class Author(models.Model):
#    """Model representing an author."""
#    first_name = models.CharField(max_length=100)
#    last_name = models.CharField(max_length=100, null=True)
#    date_of_birth = models.DateField(null=True, blank=True)
#    date_of_death = models.DateField('Died', null=True, blank=True)
#
#    class Meta:
#        ordering = ['last_name', 'first_name']
#
#    def get_absolute_url(self):
#        """Returns the url to access a particular author instance."""
#        return reverse('author-detail', args=[str(self.id)])
#
#    def __str__(self):
#        """String for representing the Model object."""
#        return f'{self.last_name}, {self.first_name}'
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
        )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


import uuid  # Required for unique book instances
from datetime import date

from django.contrib.auth.models import User  # Required to assign User as a borrower


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)

tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/catalog/views.py
from django.shortcuts import render

# Create your views here.
from catalog.models import Book, Author, BookInstance, Genre

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_genres = Genre.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_books_with_the = Book.objects.filter(title__icontains='the').count()
    
    # The 'all()' is implied by default.    
    num_authors = Author.objects.count()
    
    context = {
        'num_books': num_books,
        'num_books_with_the': num_books_with_the,
        'num_genres': num_genres,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

from django.views import generic

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author: {{ author.last }}, {{ author.first }}</h1>

<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p> 
<p><strong>Language:</strong> {{ book.language }}</p>  
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
    {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
          <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a> ({{ author.date_of_birth }} -- {{ author.date_of_death }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

tutorials/web/mdn/server-side_programming/django/django_projects/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}